# Problem 1 

In [2]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 1.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
a=np.array([8,2,4,9,5])
print(a)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a.sort()
print(a)

[8 2 4 9 5]
[2 4 5 8 9]


# Problem 2

In [15]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
a = np.array([10, 15, 30, 45, 60])
print(a)

[10 15 30 45 60]


In [16]:
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
a=np.linspace(5,15,11)
print(a)

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [17]:
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
a=np.arange(50,101,5)
print(a)

[ 50  55  60  65  70  75  80  85  90  95 100]


In [18]:
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
a=np.linspace(0,100,5)
print(a)

[  0.  25.  50.  75. 100.]


In [23]:
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
a=np.random.randint(10,30,5)
print(a)

[11 21 28 16 25]


In [22]:
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
a=np.random.uniform(-1, 1, 10)
print(a)

[-0.16545141 -0.08149336 -0.62255809  0.22579219  0.1771125   0.41724645
  0.82333913  0.13139138  0.25807484 -0.42704447]


In [24]:
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
a=np.random.randint(10,51,(3, 5))
print(a)

[[25 28 33 18 41]
 [26 10 18 12 13]
 [46 28 24 21 43]]


In [25]:
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
a=np.random.randint(10,51,(3, 5))
satirToplamlari=np.sum(a,1)
print("Satir toplamı:",satirToplamlari)

sutunToplamlari=np.sum(a,0)
print("Sutun toplamları:",sutunToplamlari)

Satir toplamı: [121 161 137]
Sutun toplamları: [ 81  77  69  82 110]


In [26]:
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
matris = np.random.randint(10, 51, (3, 5))
max = np.max(matris)
min = np.min(matris)
ortalama = np.mean(matris)
print("Matrisin en buyuk degeri:", max)
print("Matrisin en kucuk degeri:", min)
print("Matrisin ortalamasi:", ortalama)

Matrisin en buyuk degeri: 48
Matrisin en kucuk degeri: 10
Matrisin ortalamasi: 26.333333333333332


In [28]:
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
matris = np.random.randint(10, 51, (3, 5))
en_buyuk = np.argmax(matris)
print("En büyük değerin indeksi :", np.unravel_index(en_buyuk, matris.shape))

En büyük değerin indeksi (çok boyutlu indeks): (1, 3)


In [29]:
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
a= np.arange(10,21)
b= a[:3]
print(b)

[10 11 12]


In [30]:
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
a= np.arange(10,21)
print(a[::-1])

[20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# 15- Üretilen matrisin ilk satırını seçiniz.

In [ ]:
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

In [ ]:
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

In [ ]:
# 18- Üretilen matrisin her bir elemanının karesini alınız.

In [ ]:
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

