# Problem 1

In [6]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a=np.random.randint(0,10,5)
print(a)

# 3 - matris'in boyutunu öğrenin
print(a.shape)
# 4 - matris'i yeniden boyutlandırın
yeni=a.reshape(1,5)
print(yeni)
# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)

[9 1 6 3 8]
(5,)
[[9 1 6 3 8]]
1


# Problem 2

In [11]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a=np.arange(1,11,2)
print(a)
# 2 - Oluşturduğunuz matrisi parçalayın
b, c = np.split(a, 2)
# 3 - Parçalanmış matrisleri birleştirin
d = np.concatenate([b, c])

[1 3 5 7 9]


# Problem 3

In [15]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
a=np.random.choice(np.arange(5,101,2),10)
print(a)
# 2 - matris'in özelliklerini inceleyin
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[87 75 29 41 63  9 51 51 49  7]
1
(10,)
10
int32
